mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew', '1.4.1', :github_tarball => "boxen/puppet-homebrew"
mod 'repository', '2.2.0', :github_tarball => "boxen/puppet-repository"
